from fpdf import FPDF
import datetime

class FinancialReport(FPDF):
    def header(self):
        # Logo or Icon (conceptually)
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'Financial Health Check', 0, 0, 'C')
        self.ln(20)
        
        # Line break
        self.set_draw_color(0, 80, 180) # Blue
        self.set_line_width(1)
        self.line(10, 25, 200, 25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
        self.cell(0, 10, 'Generated by AI Financial Advisor Agent', 0, 0, 'R')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, f'  {label}', 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, body)
        self.ln()

def create_pdf():
    pdf = FinancialReport()
    pdf.add_page()
    
    # Title Sections
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'Comprehensive Financial Analysis', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f'Date: {datetime.date.today()}', 0, 1, 'L')
    pdf.ln(5)

    # 1. Budget Analysis
    pdf.chapter_title('1. Budget Analysis Output')
    budget_text = (
        "Based on the analysis of your transaction data, your monthly spending is currently $3,450 vs. "
        "an income of $5,000. \n\n"
        "Key Insights:\n"
        "- Housing accounts for 40% of your expenses (Recommended: <30%)\n"
        "- Dining out expenses have increased by 15% month-over-month.\n"
        "- You have a surplus of $1,550 monthly that can be optimized."
    )
    pdf.chapter_body(budget_text)

    # 2. Savings Strategy
    pdf.chapter_title('2. Savings Optimization Strategy')
    savings_text = (
        "Recommendation: High-Yield Savings Account (HYSA)\n\n"
        "Emergency Fund Goal: $20,700 (6 months of expenses)\n"
        "Current Progress: $5,000 (24%)\n\n"
        "Action Plan:\n"
        "1. Automate $800/month transfer to HYSA.\n"
        "2. Keep $500/month for short-term goals (Travel/Tech).\n"
        "3. Invest remaining $250 into low-cost Index Funds."
    )
    pdf.chapter_body(savings_text)

    # 3. Debt Reduction
    pdf.chapter_title('3. Debt Reduction Plan (Avalanche Method)')
    debt_text = (
        "Total Debt Detected: $12,500\n\n"
        "Priority 1: Credit Card A ($2,500 @ 24% APR)\n"
        "Priority 2: Student Loan ($10,000 @ 5% APR)\n\n"
        "Strategy:\n"
        "Direct all extra surplus to Credit Card A while paying minimums on Student Loan. "
        "You will be debt-free in approximately 14 months and save $850 in interest compared to standard payments."
    )
    pdf.chapter_body(debt_text)

    # Visual Placeholder
    pdf.set_fill_color(240, 240, 240)
    pdf.rect(10, pdf.get_y(), 190, 50, 'F')
    pdf.set_xy(10, pdf.get_y() + 20)
    pdf.set_font('Arial', 'I', 10)
    pdf.cell(0, 10, '[Visual Chart: Spending Distribution by Category]', 0, 1, 'C')
    pdf.ln(30)

    # Output
    output_filename = "Financial_Health_Report_Sample.pdf"
    pdf.output(output_filename, 'F')
    print(f"PDF generated successfully: {output_filename}")

if __name__ == '__main__':
    create_pdf()
